# Site settings
name: Dsteel
title: Dsteel
email: info@dsteel.com.uy
description: "Dsteel - Steel Framing - Construcción tradicinal ."
baseurl: "/dsteel"
url: "http://yourdomain.com"	

# Build settings
markdown: kramdown
permalinks: pretty
