# Site settings
name: Dsteel
title: Dsteel
email: info@dsteel.com.uy
description: "Dsteel - Steel Framing - Construcción tradicinal ."
baseurl: "/dsteel"
url: "http://yourdomain.com"
facebook_url: "https://www.facebook.com/pages/DSteel/520513834745482"

# Build settings
markdown: kramdown
permalinks: pretty
